### ISSUE TITLE
[Errno 65] Cannot connect to host

### ISSUE THREAD

**Issue by RationalWriter** [pokey/geneinfo#1]
* Gene Info version: unknown (1.0 ?)
* Python version: python3
* Operating System: macOS Sierra

### Description

##Describe what you were trying to get done.

I was attempting to run the script in terminal after successfully completing all steps in the README.md file. 

##Tell us what happened, what went wrong, and what you expected to happen.

The script runs for 0-70% (typically), before throwing an error, ending in "Cannot connect to host eutils.ncbi.nlm.nih.gov:443 ssl:True [Can not connect to eutils.ncbi.nlm.nih.gov:443 [No route to host]]"

The amount of progress made by the script is variable, and I have had the script complete once before (1 out of approx 50 attempts). 

### What I Did
```
##Paste the command(s) you ran and the output.
##If there was a crash, please include the traceback here.

geneinfo --genes genes.txt --terms terms.txt --extra-term regulation
  3%|█████▌                                                                                                                                                               | 1/30 [00:00<00:13,  2.23query/s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 710, in _create_direct_connection
    local_addr=self._local_addr)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 776, in create_connection
    raise exceptions[0]
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 763, in create_connection
    yield from self.sock_connect(sock, address)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/selector_events.py", line 451, in sock_connect
    return (yield from fut)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/selector_events.py", line 456, in _sock_connect
    sock.connect(address)
OSError: [Errno 65] No route to host

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 378, in connect
    proto = yield from self._create_connection(req)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 687, in _create_connection
    _, proto = yield from self._create_direct_connection(req)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 737, in _create_direct_connection
    (req.host, req.port, exc.strerror)) from exc
aiohttp.client_exceptions.ClientConnectorError: [Errno 65] Can not connect to eutils.ncbi.nlm.nih.gov:443 [No route to host]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/geneinfo", line 11, in <module>
    load_entry_point('geneinfo', 'console_scripts', 'geneinfo')()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/webbert/Dropbox (Personal)/Work Life/Crick PhD/My work/Subclonal Drivers/Late_Subclonal Driver genes/201612 Literature review of 87 genes/20161219 Pubmed search tool/geneinfo-master/geneinfo/cli.py", line 31, in main
    extra_term))
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/Users/webbert/Dropbox (Personal)/Work Life/Crick PhD/My work/Subclonal Drivers/Late_Subclonal Driver genes/201612 Literature review of 87 genes/20161219 Pubmed search tool/geneinfo-master/geneinfo/geneinfo.py", line 84, in process_genes
    for gene in group
  File "/Users/webbert/Dropbox (Personal)/Work Life/Crick PhD/My work/Subclonal Drivers/Late_Subclonal Driver genes/201612 Literature review of 87 genes/20161219 Pubmed search tool/geneinfo-master/geneinfo/geneinfo.py", line 23, in process_gene
    for term in terms
  File "/Users/webbert/Dropbox (Personal)/Work Life/Crick PhD/My work/Subclonal Drivers/Late_Subclonal Driver genes/201612 Literature review of 87 genes/20161219 Pubmed search tool/geneinfo-master/geneinfo/geneinfo.py", line 51, in process_search
    for data in await asyncio.gather(*fetcher.get_pages()):
  File "/usr/local/lib/python3.6/site-packages/pubmedasync/fetch.py", line 61, in _get
    async with self.session.get(url) as resp:
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client.py", line 636, in __aenter__
    self._resp = yield from self._coro
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client.py", line 230, in _request
    conn = yield from self._connector.connect(req)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 383, in connect
    .format(key, exc.strerror)) from exc
aiohttp.client_exceptions.ClientConnectorError: [Errno 65] Cannot connect to host eutils.ncbi.nlm.nih.gov:443 ssl:True [Can not connect to eutils.ncbi.nlm.nih.gov:443 [No route to host]]

```

**Comment by pokey** [comment]
@RationalWriter I just pushed an update to one of the dependencies.  Try pulling a new version of this repository and rerunning pip install.  Something like this:

```
git pull origin master
pip3 install -e .
```
